apiVersion: apps/v1
kind: Deployment
metadata:
  name: abctech-deployment
  labels:
    app: tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abc
  template:
    metadata:
      labels:
        app: abc
    spec:
      containers:
      - name: abc
        image: ajiahamed/edureka_app:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: abctech-service
spec:
  selector:
    app: abc
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort

